name: Deploy Laravel + Vite

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Checkout Repository
        uses: actions/checkout@v3

      - name: 📦 Setup Node.js & PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer

      - name: 📦 Install Dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          npm install --force
          npm run build

      - name: 🚀 Deploy ke VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/var/www/ujian-online"

      - name: 🚀 Jalankan Command di VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/ujian-online
            php artisan migrate --force
            php artisan config:clear
            npm install --force
            npm run build
            pm2 restart vite || pm2 start npm --name "vite" -- run dev
