name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main  # Jalankan hanya saat push ke branch utama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, bcmath, curl, tokenizer, zip, mysql
          coverage: none

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/laravel-app
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan queue:restart
            sudo systemctl restart php8.2-fpm
            sudo systemctl restart nginx
